version: '3.3'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /root/monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - /root/monitoring/loki-data:/var/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log/mysql:/var/log/mysql
      - /root/monitoring/promtail-data:/var/promtail

    ports:
      - "9080:9080"

    command: -config.file=/etc/promtail/config.yml

    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
